### ISSUE TITLE
[NOT AN ISSUE] You Are A Legend

### ISSUE THREAD

**Issue by MrNewb** [Mono-94/mVehicle#1]
Was looking at this with a friend, noticed you made a car in like ascii art at least I think you did. Ive been awake 2 days so maybe im far off but look at this block and lean back in your chair. 

https://github.com/Mono-94/mVehicle/blob/5bb5c40a96374d8a96293d860fb796bb3f7ccd03/client/main.lua#L313

![carrrrrrrrrrrr](https://github.com/Mono-94/mVehicle/assets/47620135/567e89cb-5b73-4459-ab54-0c577b259be4)

**Comment by Mono-94** [comment]
hahahahaha you smoke a lot hahha 🤣🤣🤣🤣🤣
