### ISSUE TITLE
Not owner of this vehicle

### ISSUE THREAD

**Issue by DevMinkh** [Mono-94/mVehicle#7]
Hello i just bought a new vehicle shop and now i can't store any vehicle after i bought one. Keys are working fine but i can't store the vehicle in any mGarage. If i delete the vehicle with /dv and set store = 1 in the database i can take out the bought vehicle.

My access to the scripts are not as much

`spawnVehicle = function(model, coords, plate)
	-- set key method
	local action = 'add'
	
    coords = vec4(coords.x, coords.y, coords.z, coords.w or GetEntityHeading(cache.ped))
    model = type(model) == 'string' and joaat(model) or model
    if not IsModelInCdimage(model) then return end
    loadModel(model)
    local veh = CreateVehicle(model, coords.x, coords.y, coords.z, coords.w, true, false)
    local netid = NetworkGetNetworkIdFromEntity(veh)
    SetVehicleHasBeenOwnedByPlayer(veh, true)
    SetNetworkIdCanMigrate(netid, true)
    SetVehicleNeedsToBeHotwired(veh, false)
    SetVehRadioStation(veh, 'OFF')
    SetVehicleFuelLevel(veh, 100.0)
    SetVehicleNumberPlateText(veh, plate or 'PDM')
    TriggerEvent("vehiclekeys:client:SetOwner", GetVehicleNumberPlateText(veh))

	-- give key
	exports.mVehicle:ItemCarKeysClient(action, GetVehicleNumberPlateText(veh))
    SetModelAsNoLongerNeeded(model)
    return veh
end`

This is the only place i can change some code like the export from your script.

Is there any way or snippet i can use to use your garage after buying a vehicle from this new shop?

LG

**Comment by Mono-94** [comment]
I have just uploaded an update.

**Comment by DevMinkh** [comment]
After the Update

![image](https://github.com/Mono-94/mVehicle/assets/39908861/c6e7ae47-dcfb-4af5-97b8-208c890b56b0)

same for new bought vehicle also for vehicles from the updated mGarage

**Comment by Mono-94** [comment]
I just solved that problem
